clear;
clc;
dataTemp = importdata('dataOutputTemp.txt');
dataHumi = importdata('dataOutputHumi.txt');
dataUltraSonic = importdata('dataOutputSoundTime.txt');
[dataTempFiltering,dataCount] = KalmanFilteringTemp(dataTemp);
[dataHumiFiltering,dataCount] = KalmanFilteringTemp(dataHumi);
[dataUltraSonicFiltering,dataCount] = KalmanFilteringTemp(dataUltraSonic);
t = 1:dataCount;
timeStart = datenum('08:00:00');
timeStop = datenum('15:00:00');
xdate = linspace(timeStart,timeStop,dataCount);
figure(1);
subplot(3,1,1);
plot(xdate,dataTemp,'b',xdate,dataTempFiltering,'r');
legend('温度测量值','经过滤波器之后的温度估计值');
xlabel('实验时间：2015年5月14日');
ylabel('温度（/℃）');
datetick('x','HH:MM');
grid on;
subplot(3,1,2);
plot(xdate,dataHumi,'b',xdate,dataHumiFiltering,'r');
legend('湿度测量值','经过滤波器之后的湿度估计值');
xlabel('实验时间：2015年5月14日');
ylabel('湿度（/%）');
datetick('x','HH:MM');
grid on;
subplot(3,1,3);
plot(xdate,dataUltraSonic,'b',xdate,dataUltraSonicFiltering,'r');
legend('声时测量值','经过滤波器之后的声时估计值');
xlabel('实验时间：2015年5月14日');
ylabel('声时（/us）');
ylim([290,293]);
datetick('x','HH:MM');
grid on;
figure(2);
n = 1;
A = polyfit(dataTempFiltering,dataUltraSonicFiltering,n);
t1 = polyval(A,dataTempFiltering);
t2 = 100000./(20.04*sqrt(dataTempFiltering+273.15));
plot(dataTempFiltering,dataUltraSonicFiltering,'k.',dataTempFiltering,t1,'r-',dataTempFiltering,t2);
legend('声时测量值','经过滤波器之后的声时估计值','理论计算声时值');
xlabel('温度（℃）');
ylabel('声时（us）');
grid on;
figure(3);
dataUltraSonicSpeed = 100000./dataUltraSonicFiltering;;
A1 = polyfit(dataTempFiltering,dataUltraSonicSpeed,2);
y1 = polyval(A1,dataTempFiltering);
y2 = 20.04*sqrt(dataTempFiltering+273.15);
plot(dataTempFiltering,dataUltraSonicSpeed,'k.',dataTempFiltering,y1,'r-',dataTempFiltering,y2);
legend('声速测量值','经过滤波器之后的声速估计值','理论计算声速值');
xlabel('温度（℃）');
ylabel('声速（m/s）');
grid on;
% title('声速与温度的函数图象');
% figure(4);
% plot(xdate,dataUltraSonic,'.');
% datetick('x','HH:MM');
% ylim([290,297]);
% xlabel('实验时间：2015年5月14日');
% ylabel('超声波声时（单位：us）')
% grid on;