clear;
clc;
dataTemp = importdata('dataOutputTemp.txt');
dataHumi = importdata('dataOutputHumi.txt');
dataUltraSonic = importdata('dataOutputSoundTime.txt');
[dataTempFiltering,dataCount] = KalmanFilteringTemp(dataTemp);
[dataHumiFiltering,dataCount] = KalmanFilteringTemp(dataHumi);
[dataUltraSonicFiltering,dataCount] = KalmanFilteringTemp(dataUltraSonic);
t = 1:dataCount;
figure(1);
subplot(3,1,1);
plot(t,dataTemp,'b',t,dataTempFiltering,'r');
legend('温度测量值','经过滤波器之后的温度估计值');
xlabel('测量次序（/次）');
ylabel('温度（/℃）');
subplot(3,1,2);
plot(t,dataHumi,'b',t,dataHumiFiltering,'r');
legend('湿度测量值','经过滤波器之后的湿度估计值');
xlabel('测量次序（/次）');
ylabel('湿度（/%）');
subplot(3,1,3);
plot(t,dataUltraSonic,'b',t,dataUltraSonicFiltering,'r');
legend('声时测量值','经过滤波器之后的声时估计值');
xlabel('测量次序（/次）');
ylabel('声时（/us）');
figure(2);
n = 1;
A = polyfit(dataUltraSonicFiltering,dataTempFiltering,n);
y1 = polyval(A,dataUltraSonicFiltering);
plot(dataUltraSonicFiltering,dataTempFiltering,'k.',dataUltraSonicFiltering,y1,'r-');